name: release
permissions:
  contents: write

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["test"]
    branches: [main]
    types:
      - completed

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Get version from gleam.toml
        id: version
        shell: bash
        run: echo $(grep version gleam.toml | sed 's/ //g' | sed 's/"//g') >> $GITHUB_OUTPUT
      - name: Push tag
        id: tag
        uses: Akryum/release-tag
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.version.outputs.version }}
      - name: Create Github release
        uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda # v2
        with:
          generate_release_notes: true
          make_latest: true
          tag_name: ${{ steps.tag.outputs.new_tag }}
      - name: Publish module on hex
        run: gleam publish --yes
        env:
          HEXPM_USER: ${{ secrets.hex_user }}
          HEXPM_PASS: ${{ secrets.hex_pass }}
      - name: Publish docs on hex
        run: gleam docs publish
        env:
          HEXPM_USER: ${{ secrets.hex_user }}
          HEXPM_PASS: ${{ secrets.hex_pass }}
